/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package laboriempresa.frames;

import ejb.stateless.CompanyBeanLocal;
import entity.Company;
import entity.JobVacancy;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.NamingException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import laboriempresa.util.GetEJB;

/**
 *
 * @author cauelt
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public MainFrame() {
        try {
            getEJB = new GetEJB();
            companyBean = getEJB.getCompany();
        } catch (NamingException ex) {
            JOptionPane.showMessageDialog(null, "ERRO FATAL: Sem comunicação com o EJB", null, WIDTH);
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            System.exit(1);
        }

        initComponents();
        this.setLocationRelativeTo(null);
        labLoginError.setVisible(false);
        dialogLogin.setLocationRelativeTo(null);
        dialogLogin.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogLogin = new javax.swing.JDialog();
        javax.swing.JLabel labLoginPassword = new javax.swing.JLabel();
        javax.swing.JLabel labLoginCNPJ = new javax.swing.JLabel();
        javax.swing.JPanel panLoginHeader2 = new javax.swing.JPanel();
        javax.swing.JLabel labLoginEmpresa2 = new javax.swing.JLabel();
        javax.swing.JLabel labLoginLogo = new javax.swing.JLabel();
        inputLoginCNPJ = new javax.swing.JFormattedTextField();
        inputLoginPassword = new javax.swing.JPasswordField();
        javax.swing.JButton buttonLoginSubmit = new javax.swing.JButton();
        labLoginError = new javax.swing.JLabel();
        javax.swing.JPanel panHeader = new javax.swing.JPanel();
        javax.swing.JLabel labEmpresa = new javax.swing.JLabel();
        javax.swing.JLabel labLogo = new javax.swing.JLabel();
        javax.swing.JPanel panelVagas = new javax.swing.JPanel();
        javax.swing.JScrollPane scrollPaneVagas = new javax.swing.JScrollPane();
        tableVagas = new javax.swing.JTable();
        javax.swing.JButton butGerVagas = new javax.swing.JButton();
        javax.swing.JLabel labEmpresa2 = new javax.swing.JLabel();
        javax.swing.JLabel labCNPJ = new javax.swing.JLabel();
        labNomeEmpresa = new javax.swing.JLabel();
        labNumCNPJ = new javax.swing.JLabel();

        dialogLogin.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        dialogLogin.setTitle("Login");
        dialogLogin.setAlwaysOnTop(true);
        dialogLogin.setResizable(false);
        dialogLogin.setSize(new java.awt.Dimension(328, 230));
        dialogLogin.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                quitProgram(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                quitProgram(evt);
            }
        });

        labLoginPassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labLoginPassword.setText("Senha:");

        labLoginCNPJ.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labLoginCNPJ.setText("CNPJ:");

        panLoginHeader2.setBackground(new java.awt.Color(255, 255, 255));
        panLoginHeader2.setPreferredSize(new java.awt.Dimension(344, 74));

        labLoginEmpresa2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labLoginEmpresa2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labLoginEmpresa2.setText("Empresa");
        labLoginEmpresa2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        labLoginLogo.setBackground(new java.awt.Color(255, 255, 255));
        labLoginLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labLoginLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboriempresa/assets/labori-logo.gif"))); // NOI18N

        org.jdesktop.layout.GroupLayout panLoginHeader2Layout = new org.jdesktop.layout.GroupLayout(panLoginHeader2);
        panLoginHeader2.setLayout(panLoginHeader2Layout);
        panLoginHeader2Layout.setHorizontalGroup(
            panLoginHeader2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panLoginHeader2Layout.createSequentialGroup()
                .add(labLoginLogo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 178, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(labLoginEmpresa2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panLoginHeader2Layout.setVerticalGroup(
            panLoginHeader2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, panLoginHeader2Layout.createSequentialGroup()
                .addContainerGap()
                .add(panLoginHeader2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(labLoginLogo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 67, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(labLoginEmpresa2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        try {
            inputLoginCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        buttonLoginSubmit.setText("Entrar");
        buttonLoginSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login(evt);
            }
        });

        labLoginError.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        labLoginError.setForeground(new java.awt.Color(100, 0, 0));
        labLoginError.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labLoginError.setText("CNPJ ou senha inválidos");

        org.jdesktop.layout.GroupLayout dialogLoginLayout = new org.jdesktop.layout.GroupLayout(dialogLogin.getContentPane());
        dialogLogin.getContentPane().setLayout(dialogLoginLayout);
        dialogLoginLayout.setHorizontalGroup(
            dialogLoginLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panLoginHeader2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
            .add(dialogLoginLayout.createSequentialGroup()
                .addContainerGap()
                .add(dialogLoginLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(labLoginCNPJ, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(labLoginPassword, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(dialogLoginLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(labLoginError, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(buttonLoginSubmit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 116, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, inputLoginPassword)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, inputLoginCNPJ, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 235, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(17, 17, 17))
        );
        dialogLoginLayout.setVerticalGroup(
            dialogLoginLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(dialogLoginLayout.createSequentialGroup()
                .add(panLoginHeader2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 31, Short.MAX_VALUE)
                .add(labLoginError)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(dialogLoginLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(labLoginCNPJ)
                    .add(inputLoginCNPJ, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(dialogLoginLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(labLoginPassword)
                    .add(inputLoginPassword, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(buttonLoginSubmit)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setLocationByPlatform(true);
        setName("frameLogin");
        setResizable(false);

        panHeader.setBackground(new java.awt.Color(255, 255, 255));
        panHeader.setPreferredSize(new java.awt.Dimension(344, 74));

        labEmpresa.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labEmpresa.setText("Empresa");
        labEmpresa.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        labLogo.setBackground(new java.awt.Color(255, 255, 255));
        labLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboriempresa/assets/labori-logo.gif"))); // NOI18N

        org.jdesktop.layout.GroupLayout panHeaderLayout = new org.jdesktop.layout.GroupLayout(panHeader);
        panHeader.setLayout(panHeaderLayout);
        panHeaderLayout.setHorizontalGroup(
            panHeaderLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panHeaderLayout.createSequentialGroup()
                .add(labLogo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 178, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(labEmpresa, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 406, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panHeaderLayout.setVerticalGroup(
            panHeaderLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, panHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .add(panHeaderLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(labLogo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 67, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(labEmpresa, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelVagas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Suas vagas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 14))); // NOI18N

        tableVagas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Nome da vaga", "Área de atuação", "Candidatos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableVagas.setColumnSelectionAllowed(true);
        scrollPaneVagas.setViewportView(tableVagas);
        tableVagas.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        butGerVagas.setText("Gerenciar vagas");

        org.jdesktop.layout.GroupLayout panelVagasLayout = new org.jdesktop.layout.GroupLayout(panelVagas);
        panelVagas.setLayout(panelVagasLayout);
        panelVagasLayout.setHorizontalGroup(
            panelVagasLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelVagasLayout.createSequentialGroup()
                .addContainerGap()
                .add(panelVagasLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(scrollPaneVagas)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, panelVagasLayout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(butGerVagas)))
                .addContainerGap())
        );
        panelVagasLayout.setVerticalGroup(
            panelVagasLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelVagasLayout.createSequentialGroup()
                .add(scrollPaneVagas, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 131, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(butGerVagas)
                .addContainerGap())
        );

        labEmpresa2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        labEmpresa2.setText("Empresa:");

        labCNPJ.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        labCNPJ.setText("CNPJ:");

        labNomeEmpresa.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        labNomeEmpresa.setText("labNomeEmpresa");

        labNumCNPJ.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        labNumCNPJ.setText("labNumCNPJ");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panHeader, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(panelVagas, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(14, 14, 14)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(labEmpresa2)
                            .add(labCNPJ))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(labNomeEmpresa)
                            .add(labNumCNPJ))
                        .add(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(panHeader, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(labEmpresa2)
                    .add(labNomeEmpresa))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(labCNPJ)
                    .add(labNumCNPJ))
                .add(20, 20, 20)
                .add(panelVagas, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(226, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quitProgram(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_quitProgram
        System.exit(0);
    }//GEN-LAST:event_quitProgram

    private void login(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login
        //company = companyBean.checkPass(inputLoginCNPJ.getText(), inputLoginPassword.getText());
        company = companyBean.checkPass("52.422.498/0001-84", "1234");
        if (company == null) {
            labLoginError.setVisible(true);
        } else {
            dialogLogin.setVisible(false);

            labNomeEmpresa.setText(company.getName());
            labNumCNPJ.setText(company.getCnpj());
            this.setVisible(true);
            loadTableVagas();
        }
    }//GEN-LAST:event_login

    private void loadTableVagas() {
        DefaultTableModel model = (DefaultTableModel) tableVagas.getModel();
        model.removeRow(0);

        List<JobVacancy> vacancies = companyBean.getAllVacancies(company);
        for (JobVacancy vacancy : vacancies) {

            Vector<Object> vector = new Vector<Object>();
            vector.add(vacancy.getName());
            vector.add(vacancy.getField());
            vector.add(1);
            model.addRow(vector);
        }

        tableVagas.setModel(model);
    }


    /**
     * @param args the command line arguments
     */
    public static void main() {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new MainFrame();
            }
        });
    }
    private GetEJB getEJB;
    private Company company;
    private CompanyBeanLocal companyBean;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog dialogLogin;
    private javax.swing.JFormattedTextField inputLoginCNPJ;
    private javax.swing.JPasswordField inputLoginPassword;
    private javax.swing.JLabel labLoginError;
    private javax.swing.JLabel labNomeEmpresa;
    private javax.swing.JLabel labNumCNPJ;
    private javax.swing.JTable tableVagas;
    // End of variables declaration//GEN-END:variables
}
