/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package laboriempresa.frames;

import ejb.stateless.CompanyBeanLocal;
import ejb.stateless.FieldBeanLocal;
import ejb.stateless.UserLaboriBeanLocal;
import entity.*;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.NamingException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;
import laboriempresa.util.GetEJB;

/**
 *
 * @author cauelt
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public MainFrame() {
        try {
            getEJB = new GetEJB();
            companyBean = getEJB.getCompany();
            userBean = getEJB.getUserLabori();
            fieldBean = getEJB.getField();
        } catch (NamingException ex) {
            JOptionPane.showMessageDialog(null, "ERRO FATAL: Sem comunicação com o EJB", null, WIDTH);
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            System.exit(1);
        }
        initComponents();
        formatComponents();

        this.setLocationRelativeTo(null);
        labLoginError.setVisible(false);
        dialogLogin.setLocationRelativeTo(null);
        dialogLogin.setVisible(true);
    }
    
    private void formatComponents() {
        // create the formatters, default, display, edit
        NumberFormatter defaultFormatter = new NumberFormatter(new DecimalFormat("#.##"));
        NumberFormatter displayFormatter = new NumberFormatter(new DecimalFormat("R$ #,###.00"));
        NumberFormatter editFormatter = new NumberFormatter(new DecimalFormat("#.##"));

        // set their value classes
        defaultFormatter.setValueClass(Float.class);
        displayFormatter.setValueClass(Float.class);
        editFormatter.setValueClass(Float.class);

        // create and set the DefaultFormatterFactory
        DefaultFormatterFactory salaryFactory =
                new DefaultFormatterFactory(defaultFormatter, displayFormatter, editFormatter);
        
        txtAdVagaSalario.setFormatterFactory(salaryFactory);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogLogin = new javax.swing.JDialog();
        javax.swing.JLabel labLoginPassword = new javax.swing.JLabel();
        javax.swing.JLabel labLoginCNPJ = new javax.swing.JLabel();
        javax.swing.JPanel panLoginHeader2 = new javax.swing.JPanel();
        javax.swing.JLabel labLoginEmpresa2 = new javax.swing.JLabel();
        javax.swing.JLabel labLoginLogo = new javax.swing.JLabel();
        inputLoginCNPJ = new javax.swing.JFormattedTextField();
        inputLoginPassword = new javax.swing.JPasswordField();
        javax.swing.JButton buttonLoginSubmit = new javax.swing.JButton();
        labLoginError = new javax.swing.JLabel();
        dialogVaga = new javax.swing.JDialog();
        scrollPaneCandidatos = new javax.swing.JScrollPane();
        tableCandidatos = new javax.swing.JTable();
        javax.swing.JLabel labVagaVaga = new javax.swing.JLabel();
        javax.swing.JLabel labVagaArea = new javax.swing.JLabel();
        javax.swing.JLabel labTableCandidatos = new javax.swing.JLabel();
        labVagaNomeVaga = new javax.swing.JLabel();
        labVagaNomeArea = new javax.swing.JLabel();
        butVagaVerCandidato = new javax.swing.JButton();
        javax.swing.JButton butVagaAtualizar = new javax.swing.JButton();
        javax.swing.JButton butVagaExcluirVaga = new javax.swing.JButton();
        javax.swing.JButton butVagaVoltar = new javax.swing.JButton();
        dialogCandidato = new javax.swing.JDialog();
        labCandEmail = new javax.swing.JLabel();
        labCandNome = new javax.swing.JLabel();
        javax.swing.JLabel labCandEmailFixed = new javax.swing.JLabel();
        javax.swing.JLabel labCandNomeFixed = new javax.swing.JLabel();
        javax.swing.JLabel labCandTelefoneFixed = new javax.swing.JLabel();
        labCandTelefone = new javax.swing.JLabel();
        javax.swing.JLabel labCandCidadeFixed = new javax.swing.JLabel();
        labCandCidade = new javax.swing.JLabel();
        javax.swing.JLabel labCandEnderecoFixed = new javax.swing.JLabel();
        labCandEndereco = new javax.swing.JLabel();
        javax.swing.JLabel labCandCEPFixed = new javax.swing.JLabel();
        labCandCEP = new javax.swing.JLabel();
        butCandVoltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        editCandInfo = new javax.swing.JEditorPane();
        javax.swing.JLabel labCandInfoFixed = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCandEducation = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableCandWorkExperience = new javax.swing.JTable();
        javax.swing.JLabel labCandInfoFixed1 = new javax.swing.JLabel();
        javax.swing.JLabel labCandInfoFixed2 = new javax.swing.JLabel();
        dialogAdicionarVaga = new javax.swing.JDialog();
        javax.swing.JLabel labAdVagaNomeFixed = new javax.swing.JLabel();
        txtAdVagaNome = new javax.swing.JTextField();
        javax.swing.JLabel labAdVagaAreaFixed = new javax.swing.JLabel();
        javax.swing.JLabel labAdVagaSalarioFixed = new javax.swing.JLabel();
        javax.swing.JLabel labAdVagaDetalhesFixed = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        editAdVagaDetalhes = new javax.swing.JEditorPane();
        javax.swing.JButton butAdVagaSalvar = new javax.swing.JButton();
        javax.swing.JButton butAdVagaCancelar = new javax.swing.JButton();
        comboAdVagaArea = new javax.swing.JComboBox();
        txtAdVagaSalario = new javax.swing.JFormattedTextField();
        dialogListarProf = new javax.swing.JDialog();
        jScrollPane6 = new javax.swing.JScrollPane();
        tableProfissionais = new javax.swing.JTable();
        javax.swing.JLabel labProfArea = new javax.swing.JLabel();
        comboProfAreas = new javax.swing.JComboBox();
        butProfVerCurriculo = new javax.swing.JButton();
        javax.swing.JButton butProfVoltar = new javax.swing.JButton();
        javax.swing.JPanel panHeader = new javax.swing.JPanel();
        javax.swing.JLabel labEmpresa = new javax.swing.JLabel();
        javax.swing.JLabel labLogo = new javax.swing.JLabel();
        javax.swing.JPanel panelVagas = new javax.swing.JPanel();
        javax.swing.JScrollPane scrollPaneVagas = new javax.swing.JScrollPane();
        tableVagas = new javax.swing.JTable();
        butVerCandidatos = new javax.swing.JButton();
        javax.swing.JButton butRefreshTableVagas = new javax.swing.JButton();
        javax.swing.JButton butAdicionarVaga = new javax.swing.JButton();
        javax.swing.JLabel labEmpresa2 = new javax.swing.JLabel();
        javax.swing.JLabel labCNPJ = new javax.swing.JLabel();
        labNomeEmpresa = new javax.swing.JLabel();
        labNumCNPJ = new javax.swing.JLabel();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableReferencias = new javax.swing.JTable();
        butRefAprovar = new javax.swing.JButton();
        butRefReprovar = new javax.swing.JButton();
        javax.swing.JButton butRefreshTableReferencias = new javax.swing.JButton();
        butRefDetalhesUsuario = new javax.swing.JButton();
        javax.swing.JButton butSair = new javax.swing.JButton();
        javax.swing.JButton butVerProf = new javax.swing.JButton();

        dialogLogin.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        dialogLogin.setTitle("Login");
        dialogLogin.setAlwaysOnTop(true);
        dialogLogin.setMinimumSize(new java.awt.Dimension(330, 245));
        dialogLogin.setResizable(false);
        dialogLogin.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                quitProgram(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                quitProgram(evt);
            }
        });

        labLoginPassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labLoginPassword.setText("Senha:");

        labLoginCNPJ.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labLoginCNPJ.setText("CNPJ:");

        panLoginHeader2.setBackground(new java.awt.Color(255, 255, 255));
        panLoginHeader2.setPreferredSize(new java.awt.Dimension(344, 74));

        labLoginEmpresa2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labLoginEmpresa2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labLoginEmpresa2.setText("Empresa");
        labLoginEmpresa2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        labLoginLogo.setBackground(new java.awt.Color(255, 255, 255));
        labLoginLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labLoginLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboriempresa/assets/labori-logo.gif"))); // NOI18N

        org.jdesktop.layout.GroupLayout panLoginHeader2Layout = new org.jdesktop.layout.GroupLayout(panLoginHeader2);
        panLoginHeader2.setLayout(panLoginHeader2Layout);
        panLoginHeader2Layout.setHorizontalGroup(
            panLoginHeader2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panLoginHeader2Layout.createSequentialGroup()
                .add(labLoginLogo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 178, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(labLoginEmpresa2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panLoginHeader2Layout.setVerticalGroup(
            panLoginHeader2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, panLoginHeader2Layout.createSequentialGroup()
                .addContainerGap()
                .add(panLoginHeader2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(labLoginLogo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 67, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(labLoginEmpresa2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        try {
            inputLoginCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        buttonLoginSubmit.setText("Entrar");
        buttonLoginSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login(evt);
            }
        });

        labLoginError.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        labLoginError.setForeground(new java.awt.Color(100, 0, 0));
        labLoginError.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labLoginError.setText("CNPJ ou senha inválidos");

        org.jdesktop.layout.GroupLayout dialogLoginLayout = new org.jdesktop.layout.GroupLayout(dialogLogin.getContentPane());
        dialogLogin.getContentPane().setLayout(dialogLoginLayout);
        dialogLoginLayout.setHorizontalGroup(
            dialogLoginLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panLoginHeader2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
            .add(dialogLoginLayout.createSequentialGroup()
                .addContainerGap()
                .add(dialogLoginLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(labLoginCNPJ, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(labLoginPassword, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(dialogLoginLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(labLoginError, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(buttonLoginSubmit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 116, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, inputLoginPassword)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, inputLoginCNPJ, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 235, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(17, 17, 17))
        );
        dialogLoginLayout.setVerticalGroup(
            dialogLoginLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(dialogLoginLayout.createSequentialGroup()
                .add(panLoginHeader2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 57, Short.MAX_VALUE)
                .add(labLoginError)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(dialogLoginLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(labLoginCNPJ)
                    .add(inputLoginCNPJ, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(dialogLoginLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(labLoginPassword)
                    .add(inputLoginPassword, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(buttonLoginSubmit)
                .add(15, 15, 15))
        );

        dialogVaga.setTitle("Detalhes da vaga");
        dialogVaga.setMaximumSize(new java.awt.Dimension(408, 290));
        dialogVaga.setMinimumSize(new java.awt.Dimension(408, 290));
        dialogVaga.setResizable(false);

        tableCandidatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nome", "Telefone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableCandidatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickTableCandidatos(evt);
            }
        });
        scrollPaneCandidatos.setViewportView(tableCandidatos);
        tableCandidatos.getColumnModel().getColumn(0).setMaxWidth(50);

        labVagaVaga.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labVagaVaga.setText("Vaga:");

        labVagaArea.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labVagaArea.setText("Área:");

        labTableCandidatos.setText("Candidatos à vaga:");

        labVagaNomeVaga.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        labVagaNomeVaga.setText("jLabel1");

        labVagaNomeArea.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        labVagaNomeArea.setText("jLabel1");

        butVagaVerCandidato.setText("Ver candidato");
        butVagaVerCandidato.setEnabled(false);
        butVagaVerCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butVagaVerCandidatoActionPerformed(evt);
            }
        });

        butVagaAtualizar.setText("Atualizar");
        butVagaAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butVagaAtualizarActionPerformed(evt);
            }
        });

        butVagaExcluirVaga.setText("Excluir vaga");
        butVagaExcluirVaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butVagaExcluirVagaActionPerformed(evt);
            }
        });

        butVagaVoltar.setText("Voltar");
        butVagaVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butVagaVoltarActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout dialogVagaLayout = new org.jdesktop.layout.GroupLayout(dialogVaga.getContentPane());
        dialogVaga.getContentPane().setLayout(dialogVagaLayout);
        dialogVagaLayout.setHorizontalGroup(
            dialogVagaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(dialogVagaLayout.createSequentialGroup()
                .addContainerGap()
                .add(dialogVagaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(scrollPaneCandidatos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .add(dialogVagaLayout.createSequentialGroup()
                        .add(labTableCandidatos, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(136, 136, 136))
                    .add(dialogVagaLayout.createSequentialGroup()
                        .add(labVagaArea, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 67, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(labVagaNomeArea, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE))
                    .add(dialogVagaLayout.createSequentialGroup()
                        .add(labVagaVaga, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 67, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(labVagaNomeVaga, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, dialogVagaLayout.createSequentialGroup()
                        .add(dialogVagaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(butVagaAtualizar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(butVagaExcluirVaga, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(dialogVagaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(butVagaVoltar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                            .add(butVagaVerCandidato, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                .addContainerGap())
        );
        dialogVagaLayout.setVerticalGroup(
            dialogVagaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(dialogVagaLayout.createSequentialGroup()
                .addContainerGap()
                .add(dialogVagaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(labVagaVaga)
                    .add(labVagaNomeVaga))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(dialogVagaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(labVagaArea)
                    .add(labVagaNomeArea))
                .add(24, 24, 24)
                .add(labTableCandidatos)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(scrollPaneCandidatos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 84, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(dialogVagaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(butVagaVerCandidato)
                    .add(butVagaAtualizar))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(dialogVagaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(butVagaExcluirVaga)
                    .add(butVagaVoltar))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        dialogCandidato.setTitle("Visualização do candidato");
        dialogCandidato.setMaximumSize(new java.awt.Dimension(587, 490));
        dialogCandidato.setMinimumSize(new java.awt.Dimension(587, 490));
        dialogCandidato.setResizable(false);

        labCandEmail.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        labCandEmail.setText("labCandEmail");

        labCandNome.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        labCandNome.setText("labCandNome");

        labCandEmailFixed.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labCandEmailFixed.setText("Email:");

        labCandNomeFixed.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labCandNomeFixed.setText("Nome:");

        labCandTelefoneFixed.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labCandTelefoneFixed.setText("Telefone:");

        labCandTelefone.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        labCandTelefone.setText("labCandTelefone");

        labCandCidadeFixed.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labCandCidadeFixed.setText("Cidade:");

        labCandCidade.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        labCandCidade.setText("labCandCidade");

        labCandEnderecoFixed.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labCandEnderecoFixed.setText("Endereço:");

        labCandEndereco.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        labCandEndereco.setText("labCandEndereco");

        labCandCEPFixed.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labCandCEPFixed.setText("CEP:");

        labCandCEP.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        labCandCEP.setText("labCandCEP");

        butCandVoltar.setText("Voltar");
        butCandVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCandVoltarActionPerformed(evt);
            }
        });

        editCandInfo.setContentType("text/html");
        editCandInfo.setEditable(false);
        editCandInfo.setText("");
        jScrollPane1.setViewportView(editCandInfo);

        labCandInfoFixed.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labCandInfoFixed.setText("Mais informações:");

        tableCandEducation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Curso", "Universidade", "Início", "Formação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableCandEducation);
        tableCandEducation.getColumnModel().getColumn(2).setMaxWidth(70);
        tableCandEducation.getColumnModel().getColumn(3).setMaxWidth(70);

        tableCandWorkExperience.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cargo", "Empresa", "Entrada", "Saída"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tableCandWorkExperience);
        tableCandWorkExperience.getColumnModel().getColumn(2).setMaxWidth(70);
        tableCandWorkExperience.getColumnModel().getColumn(3).setMaxWidth(70);

        labCandInfoFixed1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labCandInfoFixed1.setText("Formação acadêmica:");

        labCandInfoFixed2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labCandInfoFixed2.setText("Experiências profissionais:");

        org.jdesktop.layout.GroupLayout dialogCandidatoLayout = new org.jdesktop.layout.GroupLayout(dialogCandidato.getContentPane());
        dialogCandidato.getContentPane().setLayout(dialogCandidatoLayout);
        dialogCandidatoLayout.setHorizontalGroup(
            dialogCandidatoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(dialogCandidatoLayout.createSequentialGroup()
                .addContainerGap()
                .add(dialogCandidatoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1)
                    .add(jScrollPane2)
                    .add(jScrollPane3)
                    .add(labCandInfoFixed, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(labCandInfoFixed1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, labCandInfoFixed2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, dialogCandidatoLayout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(butCandVoltar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(dialogCandidatoLayout.createSequentialGroup()
                        .add(dialogCandidatoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, labCandEmailFixed, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, labCandNomeFixed, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(labCandTelefoneFixed, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))
                        .add(12, 12, 12)
                        .add(dialogCandidatoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(labCandEmail, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(labCandTelefone, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, labCandNome, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(dialogCandidatoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, labCandEnderecoFixed, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, labCandCidadeFixed, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(labCandCEPFixed, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(dialogCandidatoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, labCandEndereco, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(dialogCandidatoLayout.createSequentialGroup()
                                .add(labCandCidade, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 167, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(0, 0, Short.MAX_VALUE))
                            .add(labCandCEP, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        dialogCandidatoLayout.setVerticalGroup(
            dialogCandidatoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(dialogCandidatoLayout.createSequentialGroup()
                .addContainerGap()
                .add(dialogCandidatoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(labCandNomeFixed)
                    .add(labCandNome)
                    .add(labCandCidadeFixed)
                    .add(labCandCidade))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(dialogCandidatoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(labCandEmailFixed)
                    .add(labCandEmail)
                    .add(labCandEnderecoFixed)
                    .add(labCandEndereco))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(dialogCandidatoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(labCandTelefoneFixed)
                    .add(labCandTelefone)
                    .add(labCandCEPFixed)
                    .add(labCandCEP))
                .add(18, 18, 18)
                .add(labCandInfoFixed1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(labCandInfoFixed2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 72, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(labCandInfoFixed)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 101, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(butCandVoltar)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        dialogAdicionarVaga.setTitle("Adicionar vaga");
        dialogAdicionarVaga.setMaximumSize(new java.awt.Dimension(406, 313));
        dialogAdicionarVaga.setMinimumSize(new java.awt.Dimension(406, 313));
        dialogAdicionarVaga.setPreferredSize(new java.awt.Dimension(406, 313));
        dialogAdicionarVaga.setResizable(false);

        labAdVagaNomeFixed.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labAdVagaNomeFixed.setText("Nome da vaga:");

        labAdVagaAreaFixed.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labAdVagaAreaFixed.setText("Área da vaga:");

        labAdVagaSalarioFixed.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labAdVagaSalarioFixed.setText("Salário:");

        labAdVagaDetalhesFixed.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labAdVagaDetalhesFixed.setText("Detalhes da vaga:");

        jScrollPane4.setViewportView(editAdVagaDetalhes);

        butAdVagaSalvar.setText("Salvar");
        butAdVagaSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAdVagaSalvarActionPerformed(evt);
            }
        });

        butAdVagaCancelar.setText("Cancelar");
        butAdVagaCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAdVagaCancelarActionPerformed(evt);
            }
        });

        txtAdVagaSalario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤ #,##0.00"))));

        org.jdesktop.layout.GroupLayout dialogAdicionarVagaLayout = new org.jdesktop.layout.GroupLayout(dialogAdicionarVaga.getContentPane());
        dialogAdicionarVaga.getContentPane().setLayout(dialogAdicionarVagaLayout);
        dialogAdicionarVagaLayout.setHorizontalGroup(
            dialogAdicionarVagaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(dialogAdicionarVagaLayout.createSequentialGroup()
                .addContainerGap()
                .add(dialogAdicionarVagaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(labAdVagaNomeFixed, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(labAdVagaSalarioFixed, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(labAdVagaDetalhesFixed, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(labAdVagaAreaFixed, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(dialogAdicionarVagaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(dialogAdicionarVagaLayout.createSequentialGroup()
                        .add(butAdVagaCancelar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(butAdVagaSalvar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 142, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jScrollPane4)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, txtAdVagaNome)
                    .add(comboAdVagaArea, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(txtAdVagaSalario))
                .addContainerGap())
        );
        dialogAdicionarVagaLayout.setVerticalGroup(
            dialogAdicionarVagaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(dialogAdicionarVagaLayout.createSequentialGroup()
                .addContainerGap()
                .add(dialogAdicionarVagaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(labAdVagaNomeFixed)
                    .add(txtAdVagaNome, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(dialogAdicionarVagaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(comboAdVagaArea, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(labAdVagaAreaFixed))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(dialogAdicionarVagaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(txtAdVagaSalario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(labAdVagaSalarioFixed))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(dialogAdicionarVagaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(labAdVagaDetalhesFixed)
                    .add(jScrollPane4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 134, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(dialogAdicionarVagaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(butAdVagaSalvar)
                    .add(butAdVagaCancelar))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        tableProfissionais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Cidade", "Telefone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tableProfissionais);
        tableProfissionais.getColumnModel().getColumn(0).setMaxWidth(50);

        labProfArea.setText("Selecione a área:");

        butProfVerCurriculo.setText("Ver currículo");

        butProfVoltar.setText("Voltar");

        org.jdesktop.layout.GroupLayout dialogListarProfLayout = new org.jdesktop.layout.GroupLayout(dialogListarProf.getContentPane());
        dialogListarProf.getContentPane().setLayout(dialogListarProfLayout);
        dialogListarProfLayout.setHorizontalGroup(
            dialogListarProfLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(dialogListarProfLayout.createSequentialGroup()
                .addContainerGap()
                .add(dialogListarProfLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .add(dialogListarProfLayout.createSequentialGroup()
                        .add(labProfArea, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 89, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(comboProfAreas, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 203, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 84, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, dialogListarProfLayout.createSequentialGroup()
                        .add(butProfVerCurriculo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(butProfVoltar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        dialogListarProfLayout.setVerticalGroup(
            dialogListarProfLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(dialogListarProfLayout.createSequentialGroup()
                .addContainerGap()
                .add(dialogListarProfLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(labProfArea)
                    .add(comboProfAreas, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jScrollPane6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 136, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(dialogListarProfLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(butProfVoltar)
                    .add(butProfVerCurriculo))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("labori : Empresa");
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(596, 564));
        setMinimumSize(new java.awt.Dimension(596, 564));
        setName("frameLogin");
        setResizable(false);

        panHeader.setBackground(new java.awt.Color(255, 255, 255));
        panHeader.setPreferredSize(new java.awt.Dimension(344, 74));

        labEmpresa.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labEmpresa.setText("Empresa");
        labEmpresa.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        labLogo.setBackground(new java.awt.Color(255, 255, 255));
        labLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboriempresa/assets/labori-logo.gif"))); // NOI18N

        org.jdesktop.layout.GroupLayout panHeaderLayout = new org.jdesktop.layout.GroupLayout(panHeader);
        panHeader.setLayout(panHeaderLayout);
        panHeaderLayout.setHorizontalGroup(
            panHeaderLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panHeaderLayout.createSequentialGroup()
                .add(labLogo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 178, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(labEmpresa, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 406, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        panHeaderLayout.setVerticalGroup(
            panHeaderLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, panHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .add(panHeaderLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(labLogo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 67, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(labEmpresa, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelVagas.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Vagas disponíveis", 0, 0, new java.awt.Font("Lucida Grande", 0, 14))); // NOI18N

        tableVagas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome da vaga", "Área de atuação", "Candidatos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableVagas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickTableVagas(evt);
            }
        });
        scrollPaneVagas.setViewportView(tableVagas);
        tableVagas.getColumnModel().getColumn(0).setMaxWidth(50);
        tableVagas.getColumnModel().getColumn(1).setPreferredWidth(140);
        tableVagas.getColumnModel().getColumn(2).setPreferredWidth(120);
        tableVagas.getColumnModel().getColumn(3).setMaxWidth(80);

        butVerCandidatos.setText("Gerenciar vaga");
        butVerCandidatos.setEnabled(false);
        butVerCandidatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butVerCandidatosActionPerformed(evt);
            }
        });

        butRefreshTableVagas.setText("Atualizar");
        butRefreshTableVagas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butRefreshTableVagasActionPerformed(evt);
            }
        });

        butAdicionarVaga.setText("Adicionar vaga");
        butAdicionarVaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAdicionarVagaActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout panelVagasLayout = new org.jdesktop.layout.GroupLayout(panelVagas);
        panelVagas.setLayout(panelVagasLayout);
        panelVagasLayout.setHorizontalGroup(
            panelVagasLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelVagasLayout.createSequentialGroup()
                .addContainerGap()
                .add(panelVagasLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(panelVagasLayout.createSequentialGroup()
                        .add(butRefreshTableVagas)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(butAdicionarVaga)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 262, Short.MAX_VALUE)
                        .add(butVerCandidatos))
                    .add(scrollPaneVagas, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelVagasLayout.setVerticalGroup(
            panelVagasLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelVagasLayout.createSequentialGroup()
                .add(scrollPaneVagas, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 111, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(panelVagasLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(butVerCandidatos)
                    .add(butRefreshTableVagas)
                    .add(butAdicionarVaga))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labEmpresa2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        labEmpresa2.setText("Empresa:");

        labCNPJ.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        labCNPJ.setText("CNPJ:");

        labNomeEmpresa.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        labNomeEmpresa.setText("labNomeEmpresa");

        labNumCNPJ.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        labNumCNPJ.setText("labNumCNPJ");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Referências profissionais pendentes", 0, 0, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        tableReferencias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Cargo descrito", "Entrada", "Saída"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableReferencias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableReferenciasMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tableReferencias);

        butRefAprovar.setText("Aprovar");
        butRefAprovar.setEnabled(false);
        butRefAprovar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butRefAprovarActionPerformed(evt);
            }
        });

        butRefReprovar.setText("Reprovar");
        butRefReprovar.setEnabled(false);
        butRefReprovar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butRefReprovarActionPerformed(evt);
            }
        });

        butRefreshTableReferencias.setText("Atualizar");
        butRefreshTableReferencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butRefreshTableReferenciasActionPerformed(evt);
            }
        });

        butRefDetalhesUsuario.setText("Detalhes do usuário");
        butRefDetalhesUsuario.setEnabled(false);
        butRefDetalhesUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butRefDetalhesUsuarioActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jScrollPane5)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(butRefreshTableReferencias)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(butRefReprovar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 104, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(butRefAprovar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 104, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(butRefDetalhesUsuario)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(6, 6, 6)
                .add(jScrollPane5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 91, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(butRefAprovar)
                    .add(butRefReprovar)
                    .add(butRefreshTableReferencias)
                    .add(butRefDetalhesUsuario))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        butSair.setText("Sair");
        butSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSairActionPerformed(evt);
            }
        });

        butVerProf.setText("Listar profissionais");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panHeader, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(layout.createSequentialGroup()
                            .add(14, 14, 14)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                .add(labEmpresa2)
                                .add(labCNPJ))
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(labNomeEmpresa)
                                .add(layout.createSequentialGroup()
                                    .add(labNumCNPJ)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(butVerProf, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                        .add(layout.createSequentialGroup()
                            .addContainerGap()
                            .add(butSair, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 117, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(panelVagas, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(panHeader, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(labEmpresa2)
                            .add(labNomeEmpresa))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(labCNPJ)
                            .add(labNumCNPJ))
                        .add(20, 20, 20))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(butVerProf)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)))
                .add(panelVagas, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(butSair)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quitProgram(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_quitProgram
        System.exit(0);
    }//GEN-LAST:event_quitProgram

    private void login(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login
        company = companyBean.checkPass(inputLoginCNPJ.getText(), inputLoginPassword.getText());
        //company = companyBean.checkPass("33.468.532/0001-07", "tel666");
        if (company == null) {
            labLoginError.setVisible(true);
        } else {
            dialogLogin.setVisible(false);

            labNomeEmpresa.setText(company.getName());
            labNumCNPJ.setText(company.getCnpj());

            loadTableVagas();
            loadTableReferencias();
            this.setVisible(true);
        }
    }//GEN-LAST:event_login

    private void butVerCandidatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butVerCandidatosActionPerformed
        openVagaDialog();
    }//GEN-LAST:event_butVerCandidatosActionPerformed

    private void butRefreshTableVagasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butRefreshTableVagasActionPerformed
        loadTableVagas();
    }//GEN-LAST:event_butRefreshTableVagasActionPerformed

    private void clickTableVagas(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickTableVagas
        checkButVerCandidatosStatus();
        if ( evt.getClickCount() == 2 )
            openVagaDialog();
    }//GEN-LAST:event_clickTableVagas

    private void butVagaAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butVagaAtualizarActionPerformed
        loadTableCandidatos();
    }//GEN-LAST:event_butVagaAtualizarActionPerformed

    private void butVagaExcluirVagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butVagaExcluirVagaActionPerformed
        if (JOptionPane.showConfirmDialog(dialogVaga, "Deseja realmente exluir a vaga:\n" + workingVaga.toString() + "?", "Confirmação", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            companyBean.removeVacancy(workingVaga);
            loadTableVagas();
            dialogVaga.setVisible(false);
        }
    }//GEN-LAST:event_butVagaExcluirVagaActionPerformed

    private void butVagaVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butVagaVoltarActionPerformed
        dialogVaga.setVisible(false);
    }//GEN-LAST:event_butVagaVoltarActionPerformed

    private void clickTableCandidatos(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickTableCandidatos
        checkButVerCandidatoStatus();
        if ( evt.getClickCount() == 2) {
            workingCandidate = userBean.getById((Long)tableCandidatos.getValueAt(tableCandidatos.getSelectedRow(), 0));
            openCandidatoDialog();
        }
    }//GEN-LAST:event_clickTableCandidatos

    private void butVagaVerCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butVagaVerCandidatoActionPerformed
        workingCandidate = userBean.getById((Long)tableCandidatos.getValueAt(tableCandidatos.getSelectedRow(), 0));
        openCandidatoDialog();
    }//GEN-LAST:event_butVagaVerCandidatoActionPerformed

    private void butCandVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCandVoltarActionPerformed
        dialogCandidato.setVisible(false);
    }//GEN-LAST:event_butCandVoltarActionPerformed

    private void butAdicionarVagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAdicionarVagaActionPerformed
        comboAdVagaArea.removeAll();
        
        txtAdVagaNome.setText("");
        txtAdVagaSalario.setText("");
        
        List<Field> fieldList = fieldBean.getAll();
        for (Field field : fieldList)
            comboAdVagaArea.addItem(field);
        
        dialogAdicionarVaga.setLocationRelativeTo(null);
        dialogAdicionarVaga.setVisible(true); 
    }//GEN-LAST:event_butAdicionarVagaActionPerformed

    private void butAdVagaCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAdVagaCancelarActionPerformed
        dialogAdicionarVaga.setVisible(false);
    }//GEN-LAST:event_butAdVagaCancelarActionPerformed

    private void butAdVagaSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAdVagaSalvarActionPerformed
        if (txtAdVagaNome.getText().equals("") || txtAdVagaSalario.getText().equals(""))
            JOptionPane.showMessageDialog(dialogAdicionarVaga, "Entre com o nome e salário da vaga.", "Campos obrigatórios", WIDTH);
        else {
            JobVacancy newVacancy = new JobVacancy();
            newVacancy.setCompany(company);
            newVacancy.setName(txtAdVagaNome.getText());
            newVacancy.setSalary((Float)txtAdVagaSalario.getValue());
            newVacancy.setField((Field)comboAdVagaArea.getSelectedItem());
            newVacancy.setDescription(editAdVagaDetalhes.getText());
            
            companyBean.createVacancy(newVacancy);
            loadTableVagas();
            
            dialogAdicionarVaga.setVisible(false);
        }
    }//GEN-LAST:event_butAdVagaSalvarActionPerformed

    private void butSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_butSairActionPerformed

    private void butRefreshTableReferenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butRefreshTableReferenciasActionPerformed
        loadTableReferencias();
    }//GEN-LAST:event_butRefreshTableReferenciasActionPerformed

    private void butRefDetalhesUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butRefDetalhesUsuarioActionPerformed
        workingCandidate = (UserLabori)tableReferencias.getValueAt(tableReferencias.getSelectedRow(), 0);
        openCandidatoDialog();
    }//GEN-LAST:event_butRefDetalhesUsuarioActionPerformed

    private void tableReferenciasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableReferenciasMouseClicked
        checkButsReferenciasStatus();
        if ( evt.getClickCount() == 2 ) {
            workingCandidate = (UserLabori)tableReferencias.getValueAt(tableReferencias.getSelectedRow(), 0);
            openCandidatoDialog();
        }
    }//GEN-LAST:event_tableReferenciasMouseClicked

    private void butRefAprovarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butRefAprovarActionPerformed
        userBean.approveWorkExperience(pendingWorkExperiences.get(tableReferencias.getSelectedRow()));
        loadTableReferencias();
        checkButsReferenciasStatus();
    }//GEN-LAST:event_butRefAprovarActionPerformed

    private void butRefReprovarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butRefReprovarActionPerformed
        userBean.reproveWorkExperience(pendingWorkExperiences.get(tableReferencias.getSelectedRow()));
        loadTableReferencias();
        checkButsReferenciasStatus();
    }//GEN-LAST:event_butRefReprovarActionPerformed

    private void checkButVerCandidatoStatus() {
        if (tableCandidatos.getSelectedRow() == -1)
            butVagaVerCandidato.setEnabled(false);
        else
            butVagaVerCandidato.setEnabled(true);
    }

    private void checkButVerCandidatosStatus() {
        if (tableVagas.getSelectedRow() == -1)
            butVerCandidatos.setEnabled(false);
        else
            butVerCandidatos.setEnabled(true);
    }
    
    private void checkButsReferenciasStatus() {
        if (tableReferencias.getSelectedRow() == -1) {
            butRefAprovar.setEnabled(false);
            butRefReprovar.setEnabled(false);
            butRefDetalhesUsuario.setEnabled(false);
            
        } else {
            butRefAprovar.setEnabled(true);
            butRefReprovar.setEnabled(true);
            butRefDetalhesUsuario.setEnabled(true);
        }
    }

    private void openCandidatoDialog() {

        labCandNome.setText(workingCandidate.getName());
        labCandEmail.setText(workingCandidate.getEmail());
        labCandTelefone.setText(workingCandidate.getPhone());
        labCandCidade.setText(workingCandidate.getCity() + ", " + workingCandidate.getUf().getCode());
        labCandEndereco.setText(workingCandidate.getAddress());
        labCandCEP.setText(workingCandidate.getCep());
        editCandInfo.setText(workingCandidate.getAdditionalInformation());

        loadTableCandidatoEducation();
        loadTableCandidatoWorkExperience();

        dialogCandidato.setLocationRelativeTo(null);
        dialogCandidato.setVisible(true);
    }

    private void openVagaDialog() {
        workingVaga = companyBean.getJobVacancyById((Long)tableVagas.getValueAt(tableVagas.getSelectedRow(), 0));

        labVagaNomeVaga.setText(workingVaga.getName());
        labVagaNomeArea.setText(workingVaga.getField().getName());
        loadTableCandidatos();

        dialogVaga.setLocationRelativeTo(null);
        dialogVaga.setVisible(true);
    }

    private void loadTableCandidatoWorkExperience() {
        DefaultTableModel model = (DefaultTableModel) tableCandWorkExperience.getModel();

        Integer totalToRemover = model.getRowCount();
        for (int i=0; i<totalToRemover; i++)
            model.removeRow(0);

        Set<WorkExperience> workExperienceRecords = workingCandidate.getConfirmedWorkExperienceRecords();

        for (WorkExperience workExperience : workExperienceRecords) {
            Vector<Object> vector = new Vector<Object>();
            vector.add(workExperience.getPosition());
            vector.add(workExperience.getCompany());
            vector.add(workExperience.getStartYear());
            vector.add(workExperience.getEndYear());
            model.addRow(vector);
        }
    }

    private void loadTableCandidatoEducation() {

        DefaultTableModel model = (DefaultTableModel) tableCandEducation.getModel();

        Integer totalToRemover = model.getRowCount();
        for (int i=0; i<totalToRemover; i++)
            model.removeRow(0);

        Set<Education> educationRecords = workingCandidate.getEducationRecords();

        for (Education education : educationRecords) {
            Vector<Object> vector = new Vector<Object>();
            vector.add(education.getCurse());
            vector.add(education.getUniversity());
            vector.add(education.getStartYear());
            vector.add(education.getEndYear());
            model.addRow(vector);
        }
    }


    private void loadTableCandidatos() {

        DefaultTableModel model = (DefaultTableModel) tableCandidatos.getModel();

        Integer totalToRemover = model.getRowCount();
        for (int i=0; i<totalToRemover; i++)
            model.removeRow(0);

        List<UserLabori> candidatos = companyBean.getVacancyCandidates(workingVaga);
        for (UserLabori candidato : candidatos) {
            Vector<Object> vector = new Vector<Object>();
            vector.add(candidato.getId());
            vector.add(candidato.getName());
            vector.add(candidato.getPhone());
            model.addRow(vector);
        }
        checkButVerCandidatoStatus();
    }

    private void loadTableVagas() {
        DefaultTableModel model = (DefaultTableModel) tableVagas.getModel();

        Integer totalToRemover = model.getRowCount();
        for (int i=0; i<totalToRemover; i++)
            model.removeRow(0);

        List<JobVacancy> vacancies = companyBean.getAllVacancies(company);
        for (JobVacancy vacancy : vacancies) {
            Long candidates = companyBean.getVacancyCandidatesCount(vacancy);

            Vector<Object> vector = new Vector<Object>();
            vector.add(vacancy.getId());
            vector.add(vacancy.getName());
            vector.add(vacancy.getField());
            vector.add(candidates);
            model.addRow(vector);
        }
        checkButVerCandidatosStatus();
    }
    
    public void loadTableReferencias() {
        DefaultTableModel model = (DefaultTableModel) tableReferencias.getModel();

        pendingWorkExperiences.clear();
        Integer totalToRemover = model.getRowCount();
        for (int i=0; i<totalToRemover; i++)
            model.removeRow(0);

        List<WorkExperience> workExperiences = companyBean.getPendingWorkExperiences(company); // = companyBean.getAllVacancies(company);
        for (WorkExperience we : workExperiences) {

            Vector<Object> vector = new Vector<Object>();
            vector.add(we.getUser());
            vector.add(we.getPosition());
            vector.add(we.getStartYear());
            vector.add(we.getEndYear());
            
            pendingWorkExperiences.add(we);
            model.addRow(vector);
        }
        checkButsReferenciasStatus();
    }


    /**
     * @param args the command line arguments
     */
    public static void main() {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new MainFrame();
            }
        });
    }
    private GetEJB getEJB;
    private CompanyBeanLocal companyBean;
    private UserLaboriBeanLocal userBean;
    private FieldBeanLocal fieldBean;

    private Company company;
    private JobVacancy workingVaga;
    private UserLabori workingCandidate;
    private List<WorkExperience> pendingWorkExperiences = new ArrayList<WorkExperience>();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butCandVoltar;
    private javax.swing.JButton butProfVerCurriculo;
    private javax.swing.JButton butRefAprovar;
    private javax.swing.JButton butRefDetalhesUsuario;
    private javax.swing.JButton butRefReprovar;
    private javax.swing.JButton butVagaVerCandidato;
    private javax.swing.JButton butVerCandidatos;
    private javax.swing.JComboBox comboAdVagaArea;
    private javax.swing.JComboBox comboProfAreas;
    private javax.swing.JDialog dialogAdicionarVaga;
    private javax.swing.JDialog dialogCandidato;
    private javax.swing.JDialog dialogListarProf;
    private javax.swing.JDialog dialogLogin;
    private javax.swing.JDialog dialogVaga;
    private javax.swing.JEditorPane editAdVagaDetalhes;
    private javax.swing.JEditorPane editCandInfo;
    private javax.swing.JFormattedTextField inputLoginCNPJ;
    private javax.swing.JPasswordField inputLoginPassword;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel labCandCEP;
    private javax.swing.JLabel labCandCidade;
    private javax.swing.JLabel labCandEmail;
    private javax.swing.JLabel labCandEndereco;
    private javax.swing.JLabel labCandNome;
    private javax.swing.JLabel labCandTelefone;
    private javax.swing.JLabel labLoginError;
    private javax.swing.JLabel labNomeEmpresa;
    private javax.swing.JLabel labNumCNPJ;
    private javax.swing.JLabel labVagaNomeArea;
    private javax.swing.JLabel labVagaNomeVaga;
    private javax.swing.JScrollPane scrollPaneCandidatos;
    private javax.swing.JTable tableCandEducation;
    private javax.swing.JTable tableCandWorkExperience;
    private javax.swing.JTable tableCandidatos;
    private javax.swing.JTable tableProfissionais;
    private javax.swing.JTable tableReferencias;
    private javax.swing.JTable tableVagas;
    private javax.swing.JTextField txtAdVagaNome;
    private javax.swing.JFormattedTextField txtAdVagaSalario;
    // End of variables declaration//GEN-END:variables
}
