INSERT INTO UF (ID,CODE,NAME) VALUES (12,'AC','Acre');
INSERT INTO UF (ID,CODE,NAME) VALUES (27,'AL','Alagoas');
INSERT INTO UF (ID,CODE,NAME) VALUES (13,'AM','Amazonas');
INSERT INTO UF (ID,CODE,NAME) VALUES (16,'AP','Amap·');
INSERT INTO UF (ID,CODE,NAME) VALUES (29,'BA','Bahia');
INSERT INTO UF (ID,CODE,NAME) VALUES (23,'CE','Cear·');
INSERT INTO UF (ID,CODE,NAME) VALUES (53,'DF','Distrito Federal');
INSERT INTO UF (ID,CODE,NAME) VALUES (32,'ES','EspÌrito Santo');
INSERT INTO UF (ID,CODE,NAME) VALUES (52,'GO','Goi·s');
INSERT INTO UF (ID,CODE,NAME) VALUES (21,'MA','Maranh„o');
INSERT INTO UF (ID,CODE,NAME) VALUES (31,'MG','Minas Gerais');
INSERT INTO UF (ID,CODE,NAME) VALUES (50,'MS','Mato Grosso do Sul');
INSERT INTO UF (ID,CODE,NAME) VALUES (51,'MT','Mato Grosso');
INSERT INTO UF (ID,CODE,NAME) VALUES (15,'PA','Par·');
INSERT INTO UF (ID,CODE,NAME) VALUES (25,'PB','ParaÌba');
INSERT INTO UF (ID,CODE,NAME) VALUES (26,'PE','Pernambuco');
INSERT INTO UF (ID,CODE,NAME) VALUES (22,'PI','PiauÌ');
INSERT INTO UF (ID,CODE,NAME) VALUES (41,'PR','Paran·');
INSERT INTO UF (ID,CODE,NAME) VALUES (33,'RJ','Rio de Janeiro');
INSERT INTO UF (ID,CODE,NAME) VALUES (24,'RN','Rio Grande do Norte');
INSERT INTO UF (ID,CODE,NAME) VALUES (11,'RO','RondÙnia');
INSERT INTO UF (ID,CODE,NAME) VALUES (14,'RR','Roraima');
INSERT INTO UF (ID,CODE,NAME) VALUES (43,'RS','Rio Grande do Sul');
INSERT INTO UF (ID,CODE,NAME) VALUES (42,'SC','Santa Catarina');
INSERT INTO UF (ID,CODE,NAME) VALUES (28,'SE','Sergipe');
INSERT INTO UF (ID,CODE,NAME) VALUES (35,'SP','S„o Paulo');
INSERT INTO UF (ID,CODE,NAME) VALUES (17,'TO','Tocantins');

INSERT INTO FIELD (ID, NAME) VALUES (1000, 'AdministraÁ„o');
INSERT INTO FIELD (ID, NAME) VALUES (1002, 'Agricultura, Pecu·ria, Veterin·ria');
INSERT INTO FIELD (ID, NAME) VALUES (1003, 'AlimentaÁ„o  Gastronomia');
INSERT INTO FIELD (ID, NAME) VALUES (1004, 'Arquitetura, DecoraÁ„o, Design');
INSERT INTO FIELD (ID, NAME) VALUES (1005, 'Artes');
INSERT INTO FIELD (ID, NAME) VALUES (1006, 'Auditoria');
INSERT INTO FIELD (ID, NAME) VALUES (1007, 'CiÍncias, Pesquisa ');
INSERT INTO FIELD (ID, NAME) VALUES (1008, 'Comercial, Vendas');
INSERT INTO FIELD (ID, NAME) VALUES (1009, 'ComÈrcio Exterior, ImportaÁ„o, ExportaÁ„o');
INSERT INTO FIELD (ID, NAME) VALUES (1010, 'Compras');
INSERT INTO FIELD (ID, NAME) VALUES (1011, 'ComunicaÁ„o, TV, Cinema');
INSERT INTO FIELD (ID, NAME) VALUES (1012, 'ConstruÁ„o, ManutenÁ„o');
INSERT INTO FIELD (ID, NAME) VALUES (1013, 'Cont·bil, FinanÁas, Economia');
INSERT INTO FIELD (ID, NAME) VALUES (1014, 'Cultura, Lazer, Entretenimento');
INSERT INTO FIELD (ID, NAME) VALUES (1015, 'EducaÁ„o, Ensino, Idiomas');
INSERT INTO FIELD (ID, NAME) VALUES (1016, 'Engenharia');
INSERT INTO FIELD (ID, NAME) VALUES (1017, 'EstÈtica');
INSERT INTO FIELD (ID, NAME) VALUES (1018, 'Hotelaria, Turismo');
INSERT INTO FIELD (ID, NAME) VALUES (1019, 'Industrial, ProduÁ„o, F·brica');
INSERT INTO FIELD (ID, NAME) VALUES (1020, 'Inform·tica, TI, TelecomunicaÁıes');
INSERT INTO FIELD (ID, NAME) VALUES (1021, 'JurÌdica');
INSERT INTO FIELD (ID, NAME) VALUES (1022, 'LogÌstica');
INSERT INTO FIELD (ID, NAME) VALUES (1023, 'Marketing');
INSERT INTO FIELD (ID, NAME) VALUES (1024, 'Meio Ambiente, Ecologia');
INSERT INTO FIELD (ID, NAME) VALUES (1025, 'Moda');
INSERT INTO FIELD (ID, NAME) VALUES (1026, 'Qualidade ');
INSERT INTO FIELD (ID, NAME) VALUES (1027, 'QuÌmica, PetroquÌmica');
INSERT INTO FIELD (ID, NAME) VALUES (1028, 'Recursos Humanos');
INSERT INTO FIELD (ID, NAME) VALUES (1029, 'Sa˙de');
INSERT INTO FIELD (ID, NAME) VALUES (1030, 'Segurana');
INSERT INTO FIELD (ID, NAME) VALUES (1031, 'ServiÁos Gerais');
INSERT INTO FIELD (ID, NAME) VALUES (1032, 'ServiÁos Sociais e Comunit·rios');
INSERT INTO FIELD (ID, NAME) VALUES (1033, 'Telemarketing');
INSERT INTO FIELD (ID, NAME) VALUES (1034, 'Transportes');

INSERT INTO UNIVERSITY (ID, NAME, ADDRESS, UF_ID) VALUES (1000, 'Universidade de S„o Paulo', 'Cidade Universit·ria', 35);
INSERT INTO UNIVERSITY (ID, NAME, ADDRESS, UF_ID) VALUES (2000, 'Universidade Presbiteriana Mackenzie', 'Rua da ConsolaÁ„o 930', 35);
INSERT INTO UNIVERSITY (ID, NAME, ADDRESS, UF_ID) VALUES (3000, 'PontifÌcia Universidade CatÛlica de S„o Paulo', 'Rua MarquÍs de S„o Vicente 225', 35);

INSERT INTO COMPANY (ID, NAME, CNPJ, PASSWORD) VALUES (100, 'Carrefour', '52.422.498/0001-84', 'car123');
INSERT INTO COMPANY (ID, NAME, CNPJ, PASSWORD) VALUES (200, 'Petrobr·s', '23.837.043/0001-21', 'petr$');
INSERT INTO COMPANY (ID, NAME, CNPJ, PASSWORD) VALUES (300, 'TelefÙnica', '33.468.532/0001-07', 'tel666');

INSERT INTO JOBVACANCY (ID, NAME, COMPANY_ID, FIELD_ID, SALARY, DESCRIPTION) VALUES (100, 'Auxiliar de administraÁ„o', 100, 1000, 56034, 'Primeira descriÁ„o');
INSERT INTO JOBVACANCY (ID, NAME, COMPANY_ID, FIELD_ID, SALARY, DESCRIPTION) VALUES (200, 'Subauxiliar de administraÁ„o', 100, 1000, 32020, 'Segunda descriÁ„o');
INSERT INTO JOBVACANCY (ID, NAME, COMPANY_ID, FIELD_ID, SALARY, DESCRIPTION) VALUES (300, 'Gerente do departamento de administraÁ„o', 100, 1000, 12150, 'Terceira descriÁ„o');

INSERT INTO USERLABORI (ID, NAME, ADDRESS, ADDITIONALINFORMATION, CEP, CITY, EMAIL, PASSWORD, PHONE, FIELD_ID, UF_ID) VALUES (100, 'CauÍ ThenÛrio', 'Av S„o Paulo 1000', '<b>Linguagens:</b><br><ul><li>InglÍs</li><li>Espanhol</li><li>JaponÍs</li></ul><b>Habilidades:<br></b><ul><li>ProgramaÁ„o <i>(Python/Java)</i></li></ul>', '01319-010', 'S„o Paulo', 'cauelt@gmail.com', '1', '(11) 3212-1232', 1000, 35);
INSERT INTO USERLABORI (ID, NAME, ADDRESS, ADDITIONALINFORMATION, CEP, CITY, EMAIL, PASSWORD, PHONE, FIELD_ID, UF_ID) VALUES (200, 'Rony Clay', 'Rua dos IpÍs 200 - Ap 127', '<b>Linguagens:</b><br><ul><li>InglÍsê</li><li>Italiano</li><li>Russo</li></ul><b>Habilidades:<br></b><ul><li>ProgramaÁ„o <i>(C#/Java/Hibernate)</i></li><li>Se equilibrar num pÈ sÛ</li></ul>', '0100-111', 'S„o Paulo', 'ronyclayaa@gmail.com', 'rony99', '(11) 99872-1232', 1020, 35);

INSERT INTO JOBVACANCY_USERLABORI (APPLIEDUSERS_ID, APPLICATIONS_ID) VALUES (100, 100);
